//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestHelper.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuestHelper.Resources.CommonResource", typeof(CommonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to delete the downloaded routes?.
        /// </summary>
        public static string Albums_AreYourSureToDeleteLoadedRoutes {
            get {
                return ResourceManager.GetString("Albums_AreYourSureToDeleteLoadedRoutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have no albums yet.
        /// </summary>
        public static string Albums_ListRouteIsEmpty {
            get {
                return ResourceManager.GetString("Albums_ListRouteIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can free up memory by deleting previously loaded routes. If necessary, you can download them again..
        /// </summary>
        public static string Albums_YouCanDeleteDownloadedRoutes {
            get {
                return ResourceManager.GetString("Albums_YouCanDeleteDownloadedRoutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recording completed.
        /// </summary>
        public static string Audio_RecordCompleted {
            get {
                return ResourceManager.GetString("Audio_RecordCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Audio.
        /// </summary>
        public static string CommonMsg_Audio {
            get {
                return ResourceManager.GetString("CommonMsg_Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string CommonMsg_Cancel {
            get {
                return ResourceManager.GetString("CommonMsg_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To determine your location, you must enable the service..
        /// </summary>
        public static string CommonMsg_ForGettingCoordinatesNeedGeolocationEnabled {
            get {
                return ResourceManager.GetString("CommonMsg_ForGettingCoordinatesNeedGeolocationEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Geolocation service not available.
        /// </summary>
        public static string CommonMsg_GeolocationNotEnabled {
            get {
                return ResourceManager.GetString("CommonMsg_GeolocationNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Low network speed, hi image quality disabled.
        /// </summary>
        public static string CommonMsg_HiImageQualityDisabled {
            get {
                return ResourceManager.GetString("CommonMsg_HiImageQualityDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No.
        /// </summary>
        public static string CommonMsg_No {
            get {
                return ResourceManager.GetString("CommonMsg_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok.
        /// </summary>
        public static string CommonMsg_Ok {
            get {
                return ResourceManager.GetString("CommonMsg_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Complete and save.
        /// </summary>
        public static string CommonMsg_OkAndSave {
            get {
                return ResourceManager.GetString("CommonMsg_OkAndSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Waypoints: [pointCount].
        /// </summary>
        public static string CommonMsg_PointCount {
            get {
                return ResourceManager.GetString("CommonMsg_PointCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Retry.
        /// </summary>
        public static string CommonMsg_Repeat {
            get {
                return ResourceManager.GetString("CommonMsg_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string CommonMsg_Save {
            get {
                return ResourceManager.GetString("CommonMsg_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Steps: [stepCount].
        /// </summary>
        public static string CommonMsg_StepsCount {
            get {
                return ResourceManager.GetString("CommonMsg_StepsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Full.
        /// </summary>
        public static string CommonMsg_UseOriginalQuality {
            get {
                return ResourceManager.GetString("CommonMsg_UseOriginalQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning!.
        /// </summary>
        public static string CommonMsg_Warning {
            get {
                return ResourceManager.GetString("CommonMsg_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes.
        /// </summary>
        public static string CommonMsg_Yes {
            get {
                return ResourceManager.GetString("CommonMsg_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Feed not available, please check your connection to Internet.
        /// </summary>
        public static string Feed_ErrorLoadingFeed {
            get {
                return ResourceManager.GetString("Feed_ErrorLoadingFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на e.g. 2019.
        /// </summary>
        public static string Feed_SearchPlaceholder {
            get {
                return ResourceManager.GetString("Feed_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User authorization failed..
        /// </summary>
        public static string Login_AuthError {
            get {
                return ResourceManager.GetString("Login_AuthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authorizations....
        /// </summary>
        public static string Login_AuthorizationProcess {
            get {
                return ResourceManager.GetString("Login_AuthorizationProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter.
        /// </summary>
        public static string Login_Enter {
            get {
                return ResourceManager.GetString("Login_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter a valid email address.
        /// </summary>
        public static string Login_EnterCorrectEmail {
            get {
                return ResourceManager.GetString("Login_EnterCorrectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter the same password.
        /// </summary>
        public static string Login_EnterSamePasswords {
            get {
                return ResourceManager.GetString("Login_EnterSamePasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please fill in all fields.
        /// </summary>
        public static string Login_FillAllFields {
            get {
                return ResourceManager.GetString("Login_FillAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please fill in the username and password.
        /// </summary>
        public static string Login_FillLoginAndPassword {
            get {
                return ResourceManager.GetString("Login_FillLoginAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Continue with Google.
        /// </summary>
        public static string Login_GoogleAuth {
            get {
                return ResourceManager.GetString("Login_GoogleAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Google Authorization.
        /// </summary>
        public static string Login_GoogleAuthCaption {
            get {
                return ResourceManager.GetString("Login_GoogleAuthCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sorry, an error occurred while trying to use Google Chrome.
        /// </summary>
        public static string Login_GoogleAuthError {
            get {
                return ResourceManager.GetString("Login_GoogleAuthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect login or password!.
        /// </summary>
        public static string Login_IncorrectLoginOrPassword {
            get {
                return ResourceManager.GetString("Login_IncorrectLoginOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OR.
        /// </summary>
        public static string Login_Or {
            get {
                return ResourceManager.GetString("Login_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registration.
        /// </summary>
        public static string Login_Registration {
            get {
                return ResourceManager.GetString("Login_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User registration error. The indicated name or email address may already be taken..
        /// </summary>
        public static string Login_RegistrationError {
            get {
                return ResourceManager.GetString("Login_RegistrationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registrations....
        /// </summary>
        public static string Login_RegistrationProcess {
            get {
                return ResourceManager.GetString("Login_RegistrationProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name or E-Mail.
        /// </summary>
        public static string Login_YourLogin {
            get {
                return ResourceManager.GetString("Login_YourLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current state synchronization:.
        /// </summary>
        public static string MainPage_CurrentSyncStatus {
            get {
                return ResourceManager.GetString("MainPage_CurrentSyncStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable public access by link.
        /// </summary>
        public static string MakeRouteLink_EnableShareAccess {
            get {
                return ResourceManager.GetString("MakeRouteLink_EnableShareAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error enabling route sharing. Check your network connection..
        /// </summary>
        public static string MakeRouteLink_ErrorWhileCreatedReference {
            get {
                return ResourceManager.GetString("MakeRouteLink_ErrorWhileCreatedReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Link sharing disabled.
        /// </summary>
        public static string MakeRouteLink_PublicAccessDisabled {
            get {
                return ResourceManager.GetString("MakeRouteLink_PublicAccessDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Route sharing enabled.
        /// </summary>
        public static string MakeRouteLink_PublicAccessEnabled {
            get {
                return ResourceManager.GetString("MakeRouteLink_PublicAccessEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Link created for sharing the route.
        /// </summary>
        public static string MakeRouteLink_PublicReferenceCreated {
            get {
                return ResourceManager.GetString("MakeRouteLink_PublicReferenceCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Link copied to clipboard.
        /// </summary>
        public static string MakeRouteLink_ReferenceCopiedToClipboard {
            get {
                return ResourceManager.GetString("MakeRouteLink_ReferenceCopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New route.
        /// </summary>
        public static string NewRoute_Caption {
            get {
                return ResourceManager.GetString("NewRoute_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You create your first route. It can be represented in the form of photos, videos, your text notes, and simply as a specific place that you want to remember..
        /// </summary>
        public static string NewRoute_FirstRouteHelper {
            get {
                return ResourceManager.GetString("NewRoute_FirstRouteHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на After you create a route, you can share it by creating a link to it, or through any channel convenient for you - GoSh !, Telegram, Whatsapp, Facebook, Instagram.
        /// </summary>
        public static string NewRoute_FirstRouteHelperMore {
            get {
                return ResourceManager.GetString("NewRoute_FirstRouteHelperMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Route name:.
        /// </summary>
        public static string NewRoute_Name {
            get {
                return ResourceManager.GetString("NewRoute_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Need to fill route name.
        /// </summary>
        public static string NewRoute_NeedToFillNameRoute {
            get {
                return ResourceManager.GetString("NewRoute_NeedToFillNameRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add photos from the gallery or take photos right away in GoSh! If the photo contains geotag, you can see it on the map..
        /// </summary>
        public static string Onboarding_AddYourPhotos {
            get {
                return ResourceManager.GetString("Onboarding_AddYourPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In this piggy bank all your photos, text notes with descriptions of interesting places and events, tied to a position on the map.
        /// </summary>
        public static string Onboarding_AllYourNotes {
            get {
                return ResourceManager.GetString("Onboarding_AllYourNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Go to feed.
        /// </summary>
        public static string Onboarding_Begin {
            get {
                return ResourceManager.GetString("Onboarding_Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Let&apos;s get started soon!.
        /// </summary>
        public static string Onboarding_GoToStart {
            get {
                return ResourceManager.GetString("Onboarding_GoToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Welcome to
        ///GoSh!.
        /// </summary>
        public static string Onboarding_Hello {
            get {
                return ResourceManager.GetString("Onboarding_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can plan routes by adding points with places from other applications, for example, Google maps or Yandex.Maps.
        /// </summary>
        public static string Onboarding_PlanningRoutes {
            get {
                return ResourceManager.GetString("Onboarding_PlanningRoutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save your impressions by combining them by topic, for example: Holidays in Cyprus; Free parking; Conferences.
        /// </summary>
        public static string Onboarding_SaveYourImpression {
            get {
                return ResourceManager.GetString("Onboarding_SaveYourImpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Share your route with web link!.
        /// </summary>
        public static string Onboarding_Share {
            get {
                return ResourceManager.GetString("Onboarding_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Skip.
        /// </summary>
        public static string Onboarding_Skip {
            get {
                return ResourceManager.GetString("Onboarding_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Together is better - take a photo, record impressions with friends in one route!.
        /// </summary>
        public static string Onboarding_TogetherBetter {
            get {
                return ResourceManager.GetString("Onboarding_TogetherBetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gosh! works where there is no Internet. Record your impressions anywhere, when the network appears, data can be synchronized..
        /// </summary>
        public static string Onboarding_WorksOffline {
            get {
                return ResourceManager.GetString("Onboarding_WorksOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Right need for get your position.
        /// </summary>
        public static string Permission_Position {
            get {
                return ResourceManager.GetString("Permission_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New routes are available to you.
        /// </summary>
        public static string ReceivePush_YouHaveNewRoutes {
            get {
                return ResourceManager.GetString("ReceivePush_YouHaveNewRoutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registration.
        /// </summary>
        public static string Registration_Caption {
            get {
                return ResourceManager.GetString("Registration_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        public static string Registration_Email {
            get {
                return ResourceManager.GetString("Registration_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string Registration_Name {
            get {
                return ResourceManager.GetString("Registration_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string Registration_Password {
            get {
                return ResourceManager.GetString("Registration_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Repeat password.
        /// </summary>
        public static string Registration_PasswordRepeat {
            get {
                return ResourceManager.GetString("Registration_PasswordRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Submit.
        /// </summary>
        public static string Registration_RegistrationSubmit {
            get {
                return ResourceManager.GetString("Registration_RegistrationSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Route description.
        /// </summary>
        public static string Route_Description {
            get {
                return ResourceManager.GetString("Route_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have no points yet, you can add a new one..
        /// </summary>
        public static string Route_FirstPoint {
            get {
                return ResourceManager.GetString("Route_FirstPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        public static string RouteCreated_AddNewPoint {
            get {
                return ResourceManager.GetString("RouteCreated_AddNewPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Now you can add first point into your route..
        /// </summary>
        public static string RouteCreated_NowYouCanAddNewPoint {
            get {
                return ResourceManager.GetString("RouteCreated_NowYouCanAddNewPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The route &apos;[routeName]&apos; has been created..
        /// </summary>
        public static string RouteCreated_RouteCreatedSuccessful {
            get {
                return ResourceManager.GetString("RouteCreated_RouteCreatedSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add label to map....
        /// </summary>
        public static string RoutePoint_AddPoi {
            get {
                return ResourceManager.GetString("RoutePoint_AddPoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Address not defined.
        /// </summary>
        public static string RoutePoint_AddressAbsent {
            get {
                return ResourceManager.GetString("RoutePoint_AddressAbsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Address copied to clipboard.
        /// </summary>
        public static string RoutePoint_AddressCopiedToClipboard {
            get {
                return ResourceManager.GetString("RoutePoint_AddressCopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to delete the photo?.
        /// </summary>
        public static string RoutePoint_AreYouSureToDeletePhoto {
            get {
                return ResourceManager.GetString("RoutePoint_AreYouSureToDeletePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to delete the point?.
        /// </summary>
        public static string RoutePoint_AreYouSureToDeletePoint {
            get {
                return ResourceManager.GetString("RoutePoint_AreYouSureToDeletePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to set new coordinates?.
        /// </summary>
        public static string RoutePoint_AreYouSureToSetNewCoordinates {
            get {
                return ResourceManager.GetString("RoutePoint_AreYouSureToSetNewCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recording in progress ....
        /// </summary>
        public static string RoutePoint_AudioRecording {
            get {
                return ResourceManager.GetString("RoutePoint_AudioRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete photo.
        /// </summary>
        public static string RoutePoint_DeletingPhoto {
            get {
                return ResourceManager.GetString("RoutePoint_DeletingPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Deleting a Waypoint.
        /// </summary>
        public static string RoutePoint_DeletingPoint {
            get {
                return ResourceManager.GetString("RoutePoint_DeletingPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description not specified.
        /// </summary>
        public static string RoutePoint_DescriptionAbsent {
            get {
                return ResourceManager.GetString("RoutePoint_DescriptionAbsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit map label....
        /// </summary>
        public static string RoutePoint_EditPoi {
            get {
                return ResourceManager.GetString("RoutePoint_EditPoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error deleting point.
        /// </summary>
        public static string RoutePoint_ErrorWhileDeletingPoint {
            get {
                return ResourceManager.GetString("RoutePoint_ErrorWhileDeletingPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Coordinates copied to clipboard.
        /// </summary>
        public static string RoutePoint_GeoCoordinatesCopiedToClipboard {
            get {
                return ResourceManager.GetString("RoutePoint_GeoCoordinatesCopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shooting coordinates available.
        /// </summary>
        public static string RoutePoint_GeotagsExists {
            get {
                return ResourceManager.GetString("RoutePoint_GeotagsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name not specified.
        /// </summary>
        public static string RoutePoint_NameAbsent {
            get {
                return ResourceManager.GetString("RoutePoint_NameAbsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Waypoint&apos;s name:.
        /// </summary>
        public static string RoutePoint_PointNameEditCaption {
            get {
                return ResourceManager.GetString("RoutePoint_PointNameEditCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resolution is required to select a photo.
        /// </summary>
        public static string RoutePoint_RightNeedToPickPhoto {
            get {
                return ResourceManager.GetString("RoutePoint_RightNeedToPickPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resolution is required for sound recording.
        /// </summary>
        public static string RoutePoint_RightNeedToRecordAudio {
            get {
                return ResourceManager.GetString("RoutePoint_RightNeedToRecordAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resolution is necessary for taking photos.
        /// </summary>
        public static string RoutePoint_RightNeedToTakePhoto {
            get {
                return ResourceManager.GetString("RoutePoint_RightNeedToTakePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Point name must be filled.
        /// </summary>
        public static string RoutePoint_RouteNameMustBeFill {
            get {
                return ResourceManager.GetString("RoutePoint_RouteNameMustBeFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use them for a given point?.
        /// </summary>
        public static string RoutePoint_UseGeotagsForPoint {
            get {
                return ResourceManager.GetString("RoutePoint_UseGeotagsForPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Point&apos;s description.
        /// </summary>
        public static string RoutePointDescription_Caption {
            get {
                return ResourceManager.GetString("RoutePointDescription_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Describe this place ....
        /// </summary>
        public static string RoutePointDescription_Text {
            get {
                return ResourceManager.GetString("RoutePointDescription_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please register for creating and syncing your routes.
        /// </summary>
        public static string Routes_Register {
            get {
                return ResourceManager.GetString("Routes_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No routes found.
        /// </summary>
        public static string Routes_RoutesNotFound {
            get {
                return ResourceManager.GetString("Routes_RoutesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на routes.
        /// </summary>
        public static string Routes_StatisticsRoutesCreated {
            get {
                return ResourceManager.GetString("Routes_StatisticsRoutesCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на published.
        /// </summary>
        public static string Routes_StatisticsRoutesPublished {
            get {
                return ResourceManager.GetString("Routes_StatisticsRoutesPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About us.
        /// </summary>
        public static string ScreenAboutUsName {
            get {
                return ResourceManager.GetString("ScreenAboutUsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selection processing.
        /// </summary>
        public static string ScreenChooseWorkerName {
            get {
                return ResourceManager.GetString("ScreenChooseWorkerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Feed.
        /// </summary>
        public static string ScreenFeedName {
            get {
                return ResourceManager.GetString("ScreenFeedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Uploaded.
        /// </summary>
        public static string ScreenLoadedAlbumsName {
            get {
                return ResourceManager.GetString("ScreenLoadedAlbumsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Map.
        /// </summary>
        public static string ScreenMapName {
            get {
                return ResourceManager.GetString("ScreenMapName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        public static string ScreenOnBoardingName {
            get {
                return ResourceManager.GetString("ScreenOnBoardingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Private.
        /// </summary>
        public static string ScreenPrivateName {
            get {
                return ResourceManager.GetString("ScreenPrivateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose route which you want add new point.
        /// </summary>
        public static string ShareMsg_ChooseRouteForAddPoint {
            get {
                return ResourceManager.GetString("ShareMsg_ChooseRouteForAddPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your choose.
        /// </summary>
        public static string ShareMsg_ChooseWorker {
            get {
                return ResourceManager.GetString("ShareMsg_ChooseWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Making new point.
        /// </summary>
        public static string ShareMsg_MakingNewPoint {
            get {
                return ResourceManager.GetString("ShareMsg_MakingNewPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на After you invite your friends, you cannot delete the route. Are you sure?.
        /// </summary>
        public static string ShareRoute_AreYouSureAfterPublishYouCantDelete {
            get {
                return ResourceManager.GetString("ShareRoute_AreYouSureAfterPublishYouCantDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на After publication, the route will be available to all users in the album. Are you sure?.
        /// </summary>
        public static string ShareRoute_AreYouSureToPublishRoute {
            get {
                return ResourceManager.GetString("ShareRoute_AreYouSureToPublishRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Route access.
        /// </summary>
        public static string ShareRoute_Caption {
            get {
                return ResourceManager.GetString("ShareRoute_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contacts not found.
        /// </summary>
        public static string ShareRoute_ContactsNotFound {
            get {
                return ResourceManager.GetString("ShareRoute_ContactsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could not share route.
        /// </summary>
        public static string ShareRoute_ErrorShareRoute {
            get {
                return ResourceManager.GetString("ShareRoute_ErrorShareRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invite your friends to share your impressions with them:.
        /// </summary>
        public static string ShareRoute_InviteFriends {
            get {
                return ResourceManager.GetString("ShareRoute_InviteFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Only routes you have created can be published..
        /// </summary>
        public static string ShareRoute_PublishOnlyYourRoutes {
            get {
                return ResourceManager.GetString("ShareRoute_PublishOnlyYourRoutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The route is now available to selected users..
        /// </summary>
        public static string ShareRoute_RouteSharedToSelectedUsers {
            get {
                return ResourceManager.GetString("ShareRoute_RouteSharedToSelectedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на After synchronization, the route will be published.
        /// </summary>
        public static string ShareRoute_RouteWillBePublishAfterSync {
            get {
                return ResourceManager.GetString("ShareRoute_RouteWillBePublishAfterSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add access.
        /// </summary>
        public static string ShareRoutes_AddPersonAccess {
            get {
                return ResourceManager.GetString("ShareRoutes_AddPersonAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GoSh! album.
        /// </summary>
        public static string ShareRoutes_AlbumInGosh {
            get {
                return ResourceManager.GetString("ShareRoutes_AlbumInGosh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose a way.
        /// </summary>
        public static string ShareRoutes_ChooseCase {
            get {
                return ResourceManager.GetString("ShareRoutes_ChooseCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Upload descriptions.
        /// </summary>
        public static string ShareRoutes_ExportDescriptions {
            get {
                return ResourceManager.GetString("ShareRoutes_ExportDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Upload photos.
        /// </summary>
        public static string ShareRoutes_ExportPhotos {
            get {
                return ResourceManager.GetString("ShareRoutes_ExportPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Other.
        /// </summary>
        public static string ShareRoutes_Other {
            get {
                return ResourceManager.GetString("ShareRoutes_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на General access.
        /// </summary>
        public static string ShareRoutes_PublicAccess {
            get {
                return ResourceManager.GetString("ShareRoutes_PublicAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check your network connection.
        /// </summary>
        public static string Sync_CheckYourConnection {
            get {
                return ResourceManager.GetString("Sync_CheckYourConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sync error.
        /// </summary>
        public static string Sync_Error {
            get {
                return ResourceManager.GetString("Sync_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sync is already running..
        /// </summary>
        public static string Sync_SyncAlreadyStarted {
            get {
                return ResourceManager.GetString("Sync_SyncAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use sync when roaming?.
        /// </summary>
        public static string Sync_UseSyncInRoaming {
            get {
                return ResourceManager.GetString("Sync_UseSyncInRoaming", resourceCulture);
            }
        }
    }
}
