using Plugin.Permissions;
using Plugin.Permissions.Abstractions;
using QuestHelper.Consts;
using QuestHelper.LocalDB.Model;
using QuestHelper.Managers;
using QuestHelper.Model;
using QuestHelper.Resources;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Windows.Input;
using Xamarin.Forms;

namespace QuestHelper.ViewModel
{
    public class MakeNewRouteViewModel : INotifyPropertyChanged, IDialogEvents
    {
        public INavigation Navigation { get; set; }
        public event PropertyChangedEventHandler PropertyChanged;

        public ICommand BackNavigationCommand { get; private set; }
        public ICommand ViewPhotoCommand { get; private set; }
        public ICommand ImagesTresholdReachedCommand { get; private set; }

        public bool IsBusy { get; set; }

        private ImagesDataStoreManager _imagesDataStore;

        private AutoGeneratedRouted _autoGeneratedRoute;
        
        int _imagesPageSize = 10;
        private bool _isShowAllImages;
        private AutoGeneratedRouted.AutoGeneratedPoint _selectedRoutePoint;

        public MakeNewRouteViewModel(AutoGeneratedRouted autoGeneratedRoute)
        {
            _autoGeneratedRoute = autoGeneratedRoute;
            BackNavigationCommand = new Command(backNavigationCommand);
            ViewPhotoCommand = new Command(viewPhotoAsync);
            //ImagesTresholdReachedCommand = new Command(imagesTresholdReachedCommand);
            //_imagesDataStore = new ImagesDataStoreManager(_imagesPageSize, IsShowAllImages);
            //Images = new ObservableCollection<GalleryImage>();
        }

        private void backNavigationCommand(object obj)
        {
            Navigation.PopModalAsync();
        }

        /*private void imagesTresholdReachedCommand(object obj)
        {
            if (!IsBusy)
            {
                IsBusy = true;
                try
                {                    
                    var images = _imagesDataStore.GetItems(Images.Count);
                    foreach(var image in images)
                    {
                        Images.Add(image);
                    }
                }
                catch(Exception e)
                {
                    Console.WriteLine("imagesTresholdReachedCommand" + e.Message);
                }
                finally
                {
                    IsBusy = false;
                }
            }
        }*/

        public void CloseDialog()
        {
         
        }

        public void StartDialog()
        {
            //_imagesDataStore.LoadListImages();
            //imagesTresholdReachedCommand(new object());
            //PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("Images"));
        }

        public IEnumerable<AutoGeneratedRouted.AutoGeneratedPoint> RoutePoints => _autoGeneratedRoute.Points;

        private void viewPhotoAsync(object imageSource)
        {
            string path = string.Empty;
            var defaultViewerService = DependencyService.Get<IDefaultViewer>();
            if (imageSource is GalleryImage)
            {
                path = ((GalleryImage)imageSource).ImagePath;
            }
            if (!string.IsNullOrEmpty(path))
            {
                defaultViewerService.Show(path.Replace("_preview", ""));
            }
        }

        public AutoGeneratedRouted.AutoGeneratedPoint SelectedRoutePoint
        {
            set
            {
                if (value != _selectedRoutePoint)
                {
                    _selectedRoutePoint = value;
                    PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("SelectedRoutePoint"));
                    PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("SelectedRoutePointImages"));
                }
            }
            get => _selectedRoutePoint;
        }

        public List<string> SelectedRoutePointImages
        {
            get
            {
                return _selectedRoutePoint != null ? _selectedRoutePoint.Images : new List<string>();
            }
        }

        /*public bool IsShowAllImages
        {
            set
            {
                if (value != _isShowAllImages)
                {
                    _isShowAllImages = value;
                    _imagesDataStore = new ImagesDataStoreManager(_imagesPageSize, _isShowAllImages);
                    _imagesDataStore.LoadListImages();
                    Images = new ObservableCollection<GalleryImage>();
                    imagesTresholdReachedCommand(new object());
                    PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("Images"));
                }
            }
            get
            {
                return _isShowAllImages;
            }
        }*/
    }
}
