using System;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Windows.Input;
using QuestHelper.Model;
using Xamarin.Forms;
using static QuestHelper.Model.AutoGeneratedRouted;

namespace QuestHelper.ViewModel
{
    public class PreviewRoutePointImagesViewModel : INotifyPropertyChanged, IDialogEvents
    {
        public INavigation Navigation { get; set; }
        public event PropertyChangedEventHandler PropertyChanged;

        public ICommand DeleteImageCommand { get; private set; }
        
        private AutoGeneratedPoint _selectedPoint;

        public PreviewRoutePointImagesViewModel(AutoGeneratedRouted.AutoGeneratedPoint selectedPoint)
        {
            DeleteImageCommand = new Command(deleteImageCommand);
            _selectedPoint = selectedPoint;
        }

        private void deleteImageCommand(object obj)
        {

        }

        public void CloseDialog()
        {
            
        }

        public void StartDialog()
        {

        }

        public ObservableCollection<ViewLocalFile> Images
        {
            get
            {
                return _selectedPoint.Images;
            }
        }
    }
}
