using QuestHelper.LocalDB.Model;
using QuestHelper.Model;
using System;
using System.Collections.Generic;
using System.Text;
using QuestHelper.Resources;

namespace QuestHelper.Managers
{
    public class AutoRoutePreviewMakerManager
    {
        private LocalFileCacheManager _cacheManager;

        public AutoRoutePreviewMakerManager(LocalFileCacheManager cacheManager)
        {
            _cacheManager = cacheManager;
        }

        internal AutoGeneratedRouted Make(DateTimeOffset periodStart, DateTimeOffset periodEnd)
        {
            AutoGeneratedRouted route = new AutoGeneratedRouted(new ImageManager());

            var localCacheFiles =  _cacheManager.GetImagesInfo(periodStart, periodEnd);
            if (localCacheFiles.Count > 0)
            {
                
                route.Name = $"{CommonResource.AutoRoutes_RouteName} { periodStart.DateTime.ToShortDateString() } - { periodEnd.DateTime.ToShortDateString() }";
                route.BuildOld(localCacheFiles); 
            }
            return route;
        }
    }

}
