using QuestHelper.LocalDB.Model;
using QuestHelper.Model;
using System;
using System.Collections.Generic;
using System.Text;

namespace QuestHelper.Managers
{
    public class AutoRouteMakerManager
    {
        internal AutoGeneratedRoute Make(int depthInDays, string creatorId)
        {
            AutoGeneratedRoute route = new AutoGeneratedRoute(new ImageManager());
            ImagesDataStoreManager imagesGalleryManager = new ImagesDataStoreManager(50, false, depthInDays);
            imagesGalleryManager.LoadListImages();
            if (imagesGalleryManager.Count() > 0)
            {
                route.SourceGalleryImages = imagesGalleryManager.GetItems(0);
                route.Name = "Мой маршрут за 7 дней";
                //route.Build();
            }
            return route;
        }
    }

}
