using System;
using QuestHelper.LocalDB.Model;
using QuestHelper.Model;

namespace QuestHelper.Managers
{
    public class AutoRouteMakerManager
    {
        public AutoRouteMakerManager()
        {
        }

        public bool Make(AutoGeneratedRouted autoRoute, string creatorId)
        {
            if (autoRoute.Points.Count > 0)
            {
                var vroute = new ViewRoute(string.Empty);
                vroute.CreatorId = creatorId;
                vroute.CreateDate = DateTime.Now;
                vroute.Description = "Автоматически созданный маршрут";
                vroute.Name = autoRoute.Name;
                if (vroute.Save())
                {
                    foreach (var autoPoint in autoRoute.Points)
                    {
                        var vroutePoint = new ViewRoutePoint(vroute.RouteId, string.Empty);
                        vroutePoint.Name = autoPoint.Name;
                        vroutePoint.Longitude = autoPoint.Longitude;
                        vroutePoint.Latitude = autoPoint.Latitude;
                        vroutePoint.Version++;
                        if (vroutePoint.Save())
                        {
                            foreach(var autoMedia in autoPoint.Images)
                            {
                                vroutePoint.AddMediaItem(autoMedia.Id, MediaObjectTypeEnum.Image);
                            }
                            vroutePoint.Save();
                        }
                    }
                    return true;
                }
            }


            return false;
        }
    }
}
